INSERT  INTO `country`(`id`,`name`,`official_state_name`,`code`) VALUES 
(1,'Afghanistan','The Islamic Republic of Afghanistan','AF'),
(2,'Aland Islands','Aland','AX'),
(3,'Albania','The Republic of Albania','AL'),
(4,'Algeria','The People\'s Democratic Republic of Algeria','DZ'),
(5,'American Samoa','The Territory of American Samoa','AS'),
(6,'Andorra','The Principality of Andorra','AD'),
(7,'Angola','The Republic of Angola','AO'),
(8,'Anguilla','Anguilla','AI'),
(9,'Antarctica','All land and ice shelves south of the 60th parallel south','AQ'),
(10,'Antigua and Barbuda','Antigua and Barbuda','AG'),
(11,'Argentina','The Argentine Republic','AR'),
(12,'Armenia','The Republic of Armenia','AM'),
(13,'Aruba','Aruba','AW'),
(14,'Australia','The Commonwealth of Australia','AU'),
(15,'Austria','The Republic of Austria','AT'),
(16,'Azerbaijan','The Republic of Azerbaijan','AZ'),
(17,'Bahamas','The Commonwealth of The Bahamas','BS'),
(18,'Bahrain','The Kingdom of Bahrain','BH'),
(19,'Bangladesh','The People\'s Republic of Bangladesh','BD'),
(20,'Barbados','Barbados','BB'),
(21,'Belarus','The Republic of Belarus','BY'),
(22,'Belgium','The Kingdom of Belgium','BE'),
(23,'Belize','Belize','BZ'),
(24,'Benin','The Republic of Benin','BJ'),
(25,'Bermuda','Bermuda','BM'),
(26,'Bhutan','The Kingdom of Bhutan','BT'),
(27,'Bolivia','The Plurinational State of Bolivia','BO'),
(28,'Bonaire, Sint Eustatius and Saba','Bonaire, Sint Eustatius and Saba','BQ'),
(29,'Bosnia and Herzegovina','Bosnia and Herzegovina','BA'),
(30,'Botswana','The Republic of Botswana','BW'),
(31,'Bouvet Island','Bouvet Island','BV'),
(32,'Brazil','The Federative Republic of Brazil','BR'),
(33,'British Indian Ocean Territory','The British Indian Ocean Territory','IO'),
(34,'Brunei Darussalam','The Nation of Brunei, the Abode of Peace','BN'),
(35,'Bulgaria','The Republic of Bulgaria','BG'),
(36,'Burkina Faso','Burkina Faso','BF'),
(37,'Burundi','The Republic of Burundi','BI'),
(38,'Cabo Verde','The Republic of Cabo Verde','CV'),
(39,'Cambodia','The Kingdom of Cambodia','KH'),
(40,'Cameroon','The Republic of Cameroon','CM'),
(41,'Canada','Canada','CA'),
(42,'Cayman Islands','The Cayman Islands','KY'),
(43,'Central African Republic','The Central African Republic','CF'),
(44,'Chad','The Republic of Chad','TD'),
(45,'Chile','The Republic of Chile','CL'),
(46,'China','The People\'s Republic of China','CN'),
(47,'Christmas Island','The Territory of Christmas Island','CX'),
(48,'Cocos (Keeling) Islands','The Territory of Cocos (Keeling) Islands','CC'),
(49,'Colombia','The Republic of Colombia','CO'),
(50,'Comoros','The Union of the Comoros','KM'),
(51,'Congo','The Republic of the Congo','CG'),
(52,'DR Congo','The Democratic Republic of the Congo','CD'),
(53,'Cook Islands','The Cook Islands','CK'),
(54,'Costa Rica','The Republic of Costa Rica','CR'),
(55,'Co´te d\'Ivoire','The Republic of Co´te d\'Ivoire','CI'),
(56,'Croatia','The Republic of Croatia','HR'),
(57,'Cuba','The Republic of Cuba','CU'),
(58,'Curacao','The Country of Curacao','CW'),
(59,'Cyprus','The Republic of Cyprus','CY'),
(60,'Czech Republic','The Czech Republic','CZ'),
(61,'Denmark','The Kingdom of Denmark','DK'),
(62,'Djibouti','The Republic of Djibouti','DJ'),
(63,'Dominica','The Commonwealth of Dominica','DM'),
(64,'Dominican Republic','The Dominican Republic','DO'),
(65,'Ecuador','The Republic of Ecuador','EC'),
(66,'Egypt','The Arab Republic of Egypt','EG'),
(67,'El Salvador','The Republic of El Salvador','SV'),
(68,'Equatorial Guinea','The Republic of Equatorial Guinea','GQ'),
(69,'Eritrea','The State of Eritrea','ER'),
(70,'Estonia','The Republic of Estonia','EE'),
(71,'Eswatini','The Kingdom of Eswatini','SZ'),
(72,'Ethiopia','The Federal Democratic Republic of Ethiopia','ET'),
(73,'Falkland Islands (Malvinas)','The Falkland Islands','FK'),
(74,'Faroe Islands','The Faroe Islands','FO'),
(75,'Fiji','The Republic of Fiji','FJ'),
(76,'Finland','The Republic of Finland','FI'),
(77,'France','The French Republic','FR'),
(78,'French Guiana','Guyane','GF'),
(79,'French Polynesia','French Polynesia','PF'),
(80,'French Southern Territories','The French Southern and Antarctic Lands','TF'),
(81,'Gabon','The Gabonese Republic','GA'),
(82,'Gambia','The Republic of The Gambia','GM'),
(83,'Georgia','Georgia','GE'),
(84,'Germany','The Federal Republic of Germany','DE'),
(85,'Ghana','The Republic of Ghana','GH'),
(86,'Gibraltar','Gibraltar','GI'),
(87,'Greece','The Hellenic Republic','GR'),
(88,'Greenland','Kalaallit Nunaat','GL'),
(89,'Grenada','Grenada','GD'),
(90,'Guadeloupe','Guadeloupe','GP'),
(91,'Guam','The Territory of Guam','GU'),
(92,'Guatemala','The Republic of Guatemala','GT'),
(93,'Guernsey','The Bailiwick of Guernsey','GG'),
(94,'Guinea','The Republic of Guinea','GN'),
(95,'Guinea-Bissau','The Republic of Guinea-Bissau','GW'),
(96,'Guyana','The Co-operative Republic of Guyana','GY'),
(97,'Haiti','The Republic of Haiti','HT'),
(98,'Heard Island and McDonald Islands','The Territory of Heard Island and McDonald Islands','HM'),
(99,'Holy See (Vatican City State)','The Holy See','VA'),
(100,'Honduras','The Republic of Honduras','HN'),
(101,'Hong Kong','The Hong Kong Special Administrative Region of China','HK'),
(102,'Hungary','Hungary','HU'),
(103,'Iceland','Iceland','IS'),
(104,'India','The Republic of India','IN'),
(105,'Indonesia','The Republic of Indonesia','ID'),
(106,'Iran','The Islamic Republic of Iran','IR'),
(107,'Iraq','The Republic of Iraq','IQ'),
(108,'Ireland','Ireland','IE'),
(109,'Isle of Man','The Isle of Man','IM'),
(110,'Israel','The State of Israel','IL'),
(111,'Italy','The Italian Republic','IT'),
(112,'Jamaica','Jamaica','JM'),
(113,'Japan','Japan','JP'),
(114,'Jersey','The Bailiwick of Jersey','JE'),
(115,'Jordan','The Hashemite Kingdom of Jordan','JO'),
(116,'Kazakhstan','The Republic of Kazakhstan','KZ'),
(117,'Kenya','The Republic of Kenya','KE'),
(118,'Kiribati','The Republic of Kiribati','KI'),
(119,'North Korea','The Democratic People\'s Republic of Korea','KP'),
(120,'South Korea','The Republic of Korea','KR'),
(121,'Kuwait','The State of Kuwait','KW'),
(122,'Kyrgyzstan','The Kyrgyz Republic','KG'),
(123,'Lao People\'s Democratic Republic','The Lao People\'s Democratic Republic','LA'),
(124,'Latvia','The Republic of Latvia','LV'),
(125,'Lebanon','The Lebanese Republic','LB'),
(126,'Lesotho','The Kingdom of Lesotho','LS'),
(127,'Liberia','The Republic of Liberia','LR'),
(128,'Libya','The State of Libya','LY'),
(129,'Liechtenstein','The Principality of Liechtenstein','LI'),
(130,'Lithuania','The Republic of Lithuania','LT'),
(131,'Luxembourg','The Grand Duchy of Luxembourg','LU'),
(132,'Macao','The Macao Special Administrative Region of China','MO'),
(133,'North Macedonia','The Republic of North Macedonia','MK'),
(134,'Madagascar','The Republic of Madagascar','MG'),
(135,'Malawi','The Republic of Malawi','MW'),
(136,'Malaysia','Malaysia','MY'),
(137,'Maldives','The Republic of Maldives','MV'),
(138,'Mali','The Republic of Mali','ML'),
(139,'Malta','The Republic of Malta','MT'),
(140,'Marshall Islands','The Republic of the Marshall Islands','MH'),
(141,'Martinique','Martinique','MQ'),
(142,'Mauritania','The Islamic Republic of Mauritania','MR'),
(143,'Mauritius','The Republic of Mauritius','MU'),
(144,'Mayotte','The Department of Mayotte','YT'),
(145,'Mexico','The United Mexican States','MX'),
(146,'Micronesia','The Federated States of Micronesia','FM'),
(147,'Moldova','The Republic of Moldova','MD'),
(148,'Monaco','The Principality of Monaco','MC'),
(149,'Mongolia','Mongolia','MN'),
(150,'Montenegro','Montenegro','ME'),
(151,'Montserrat','Montserrat','MS'),
(152,'Morocco','The Kingdom of Morocco','MA'),
(153,'Mozambique','The Republic of Mozambique','MZ'),
(154,'Myanmar','The Republic of the Union of Myanmar','MM'),
(155,'Namibia','The Republic of Namibia','NA'),
(156,'Nauru','The Republic of Nauru','NR'),
(157,'Nepal','The Federal Democratic Republic of Nepal','NP'),
(158,'Netherlands','The Kingdom of the Netherlands','NL'),
(159,'New Caledonia','New Caledonia','NC'),
(160,'New Zealand','New Zealand','NZ'),
(161,'Nicaragua','The Republic of Nicaragua','NI'),
(162,'Niger','The Republic of the Niger','NE'),
(163,'Nigeria','The Federal Republic of Nigeria','NG'),
(164,'Niue','Niue','NU'),
(165,'Norfolk Island','The Territory of Norfolk Island','NF'),
(166,'Northern Mariana Islands','The Commonwealth of the Northern Mariana Islands','MP'),
(167,'Norway','The Kingdom of Norway','NO'),
(168,'Oman','The Sultanate of Oman','OM'),
(169,'Pakistan','The Islamic Republic of Pakistan','PK'),
(170,'Palau','The Republic of Palau','PW'),
(171,'Palestine','The State of Palestine','PS'),
(172,'Panama','The Republic of Panama','PA'),
(173,'Papua New Guinea','The Independent State of Papua New Guinea','PG'),
(174,'Paraguay','The Republic of Paraguay','PY'),
(175,'Peru','The Republic of Peru','PE'),
(176,'Philippines','The Republic of the Philippines','PH'),
(177,'Pitcairn','The Pitcairn, Henderson, Ducie and Oeno Islands','PN'),
(178,'Poland','The Republic of Poland','PL'),
(179,'Portugal','The Portuguese Republic','PT'),
(180,'Puerto Rico','The Commonwealth of Puerto Rico','PR'),
(181,'Qatar','The State of Qatar','QA'),
(182,'Reunion','Reunion','RE'),
(183,'Romania','Romania','RO'),
(184,'Russia','The Russian Federation','RU'),
(185,'Rwanda','The Republic of Rwanda','RW'),
(186,'Saint Barthelemy','The Collectivity of Saint-Barthelemy','BL'),
(187,'Saint Helena, Ascension and Tristan da Cunha','Saint Helena, Ascension and Tristan da Cunha','SH'),
(188,'Saint Kitts and Nevis','Saint Kitts and Nevis','KN'),
(189,'Saint Lucia','Saint Lucia','LC'),
(190,'Saint Martin (French part)','The Collectivity of Saint-Martin','MF'),
(191,'Saint Pierre and Miquelon','The Overseas Collectivity of Saint-Pierre and Miquelon','PM'),
(192,'Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','VC'),
(193,'Samoa','The Independent State of Samoa','WS'),
(194,'San Marino','The Republic of San Marino','SM'),
(195,'Sao Tome and Principe','The Democratic Republic of Sao Tome and Principe','ST'),
(196,'Saudi Arabia','The Kingdom of Saudi Arabia','SA'),
(197,'Senegal','The Republic of Senegal','SN'),
(198,'Serbia','The Republic of Serbia','RS'),
(199,'Seychelles','The Republic of Seychelles','SC'),
(200,'Sierra Leone','The Republic of Sierra Leone','SL'),
(201,'Singapore','The Republic of Singapore','SG'),
(202,'Sint Maarten (Dutch part)','Sint Maarten','SX'),
(203,'Slovakia','The Slovak Republic','SK'),
(204,'Slovenia','The Republic of Slovenia','SI'),
(205,'Solomon Islands','The Solomon Islands','SB'),
(206,'Somalia','The Federal Republic of Somalia','SO'),
(207,'South Africa','The Republic of South Africa','ZA'),
(208,'South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands','GS'),
(209,'South Sudan','The Republic of South Sudan','SS'),
(210,'Spain','The Kingdom of Spain','ES'),
(211,'Sri Lanka','The Democratic Socialist Republic of Sri Lanka','LK'),
(212,'Sudan','The Republic of the Sudan','SD'),
(213,'Suriname','The Republic of Suriname','SR'),
(214,'Svalbard and Jan Mayen','Svalbard and Jan Mayen','SJ'),
(215,'Sweden','The Kingdom of Sweden','SE'),
(216,'Switzerland','The Swiss Confederation','CH'),
(217,'Syrian Arab Republic','The Syrian Arab Republic','SY'),
(218,'Taiwan','The Republic of China','TW'),
(219,'Tajikistan','The Republic of Tajikistan','TJ'),
(220,'Tanzania','The United Republic of Tanzania','TZ'),
(221,'Thailand','The Kingdom of Thailand','TH'),
(222,'Timor-Leste','The Democratic Republic of Timor-Leste','TL'),
(223,'Togo','The Togolese Republic','TG'),
(224,'Tokelau','Tokelau','TK'),
(225,'Tonga','The Kingdom of Tonga','TO'),
(226,'Trinidad and Tobago','The Republic of Trinidad and Tobago','TT'),
(227,'Tunisia','The Republic of Tunisia','TN'),
(228,'Turkiye','The Republic of Turkiye','TR'),
(229,'Turkmenistan','Turkmenistan','TM'),
(230,'Turks and Caicos Islands','The Turks and Caicos Islands','TC'),
(231,'Tuvalu','Tuvalu','TV'),
(232,'Uganda','The Republic of Uganda','UG'),
(233,'Ukraine','Ukraine','UA'),
(234,'United Arab Emirates','The United Arab Emirates','AE'),
(235,'United Kingdom','The United Kingdom of Great Britain and Northern Ireland','GB'),
(236,'United States','The United States of America','US'),
(237,'United States Minor Outlying Islands','Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island','UM'),
(238,'Uruguay','The Oriental Republic of Uruguay','UY'),
(239,'Uzbekistan','The Republic of Uzbekistan','UZ'),
(240,'Vanuatu','The Republic of Vanuatu','VU'),
(241,'Venezuela','The Bolivarian Republic of Venezuela','VE'),
(242,'Viet Nam','The Socialist Republic of Viet Nam','VN'),
(243,'Virgin Islands, British','The Virgin Islands','VG'),
(244,'Virgin Islands, U.S.','The Virgin Islands of the United States','VI'),
(245,'Wallis and Futuna','The Territory of the Wallis and Futuna Islands','WF'),
(246,'Western Sahara','The Sahrawi Arab Democratic Republic','EH'),
(247,'Yemen','The Republic of Yemen','YE'),
(248,'Zambia','The Republic of Zambia','ZM'),
(249,'Zimbabwe','The Republic of Zimbabwe','ZW');