/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
        mellon: {
          primary: "#DBA506",
          contrast: "#000000",
          shade: "#c19105",
          tint: "#dfae1f",
        },
        onyx: {
          primary: "#282C2F",
          primary: {
            0: "#000000",
            5: "#0c0d0e",
            10: "#171a1c",
            15: "#232729",
            default: "#282C2F",
            20: "#2f3437",
            25: "#3b4045",
            30: "#464d53",
            35: "#525a60",
            40: "#5e676e",
            45: "#6a747c",
            50: "#75818a",
            55: "#838d95",
            60: "#919aa1",
            65: "#9fa7ad",
            70: "#acb3b9",
            75: "#bac0c4",
            80: "#c8cdd0",
            85: "#d6d9dc",
            90: "#e3e6e8",
            95: "#f1f2f3",
            100: "#ffffff",
          },
          contrast: "#ffffff",
          // contrast: '#D6D6D7',
          shade: "#202124",
          tint: "#323639",
        },
      },
      width: {
        96: "24rem",
        "movie-cast-profile": "300px",
      },
      height: {
        "movie-cast-profile": "300px",
        "movie-image": "400px",
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [],
};
